### ISSUE TITLE
Phrase peu comprehensible.

### ISSUE THREAD

**Issue by KylianLEGUEN-zz** [IamHenri/G1-Geometrie#1]
Une des phrases du document (chapitre-2-les-coordonnees-cartesiennes.html) est peu comprehensible :

_"Sur cet droite graduée, 0 est l'origine du repère, le ses positif de parcours de cette droite est des négatifs vers les positifs. "_ :
**"le ses positif de parcours"**, il semble y avoir une erreur.

**Comment by IamHenri** [comment]
ok merci pas ses mais sens!!!
Correction faite
