### ISSUE TITLE
Don de ressources

### ISSUE THREAD

**Issue by KylianLEGUEN-zz** [IamHenri/G1-Geometrie#2]
Je donne en open source mes documents,
sur les dérivées, primitives, et quelques rappels utiles.

Les documents ont été formatés au format latex

[Derivees_Primitives_Ressources.zip](https://github.com/IamHenri/G1-Geometrie/files/8288684/Derivees_Primitives_Ressources.zip)

**Comment by IamHenri** [comment]
Merci
Mais préférez coller les scripts directement
