### ISSUE TITLE
L’URL ne fonctionne pas.

### ISSUE THREAD

**Issue by phnix-dev** [IamHenri/G1-Geometrie#3]
Lorsque on clique sur l'adresse https://iamhenri.github.io/G1-Geometrie/ on est redirigé sur le site http://sansaccenttoutattache.fr/.
On ne peut plus accéder aux cours.

**Comment by IamHenri** [comment]
oui erreur de ma part suite à un mauvais paramétrage 
correction appliquée et normalement rétablissement dans l'ordre sous peu
