### ISSUE TITLE
Quaternions 

### ISSUE THREAD

**Issue by phnix-dev** [IamHenri/G1-Geometrie#4]
La valeur de b ne doit-elle pas être 0, pour l'identité ?
Et la valeur de b ne doit-elle pas être 1, pour la rotation en x ?
![image](https://user-images.githubusercontent.com/76911907/198264856-6143031d-882b-4a05-991c-c55195430323.png)

**Comment by IamHenri** [comment]
Oui, merci grosse typo! 
je corrige

**Comment by phnix-dev** [comment]
Je crois que vous avez oublié la ligne identité: b devrait être a 0
![IMG_20221101_161401.jpg](https://user-images.githubusercontent.com/76911907/199268509-fa8cfd2c-196e-4f78-b6fa-8fb7bf8a3697.jpg)

**Comment by IamHenri** [comment]
corrigé, merci. 
Pour infos : 
a = 1 pour avoir l'identité. q = 1 est le quaternion qui représente l'identité pour le produit (q*= q = 1). Pour tout quaternion r qr = r, donc a fortiori pour les quaternions dont la partie réelle est nulle. En espérant vous avoir répondu
